services:
  - type: web
    name: flask-sms
    env: python
    rootDir: flask_sms
    buildCommand: "./build.sh"
    startCommand: "gunicorn run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: FLASK_CONFIG
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sms-db
          property: connectionString

databases:
  - name: sms-db
    databaseName: sms
    user: sms_user
    plan: free
